(source gnu)
(source melpa)

(depends-on "cask")
(depends-on "color-theme")
(depends-on "color-theme-sanityinc-tomorrow")
(depends-on "dash")
(depends-on "epl")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-haskell")
(depends-on "haskell-mode")
(depends-on "pallet")
(depends-on "paredit")
(depends-on "rainbow-delimiters")
(depends-on "s")
(depends-on "smex")